### ISSUE TITLE
Configuration file doesn't exist.

### ISSUE THREAD

**Issue by andrewfabrizi** [gsoft-inc/azure-devops-npm-auth#8]
I am trying to use azure-devops-npm-auth in a directory that does not contain a .npmrc file.

**Requirement**
The use case for this is to create a react app from a react template package that exists in a private registry. Example: npx create-react-app my-app --template @private-registry/cra-template-typescript

**Issue**
I am receiving the error below:

C:\Users\andrewfabrizi\source>azure-devops-npm-auth
C:\Users\andrewfabrizi\AppData\Roaming\npm\node_modules\azure-devops-npm-auth\dist\npm-config\ini-config.js:16
                throw new Error(`Configuration file at '${filePath}' doesn't exist.`);
                ^

Error: Configuration file at 'C:\Users\andrewfabrizi\source\.npmrc' doesn't exist.
    at new IniConfig (C:\Users\andrewfabrizi\AppData\Roaming\npm\node_modules\azure-devops-npm-auth\dist\npm-config\ini-config.js:16:23)
    at new NpmConfig (C:\Users\andrewfabrizi\AppData\Roaming\npm\node_modules\azure-devops-npm-auth\dist\npm-config\index.js:15:9)
    at new ProjectNpmConfig (C:\Users\andrewfabrizi\AppData\Roaming\npm\node_modules\azure-devops-npm-auth\dist\npm-config\index.js:51:9)
    at Object.<anonymous> (C:\Users\andrewfabrizi\AppData\Roaming\npm\node_modules\azure-devops-npm-auth\dist\index.js:20:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)

**Workaround**
If I create an empty .npmrc file in the current directory here: C:\Users\andrewfabrizi\source\.npmrc, it works and adds the tokens to the user config .npmrc here: C:\Users\andrewfabrizi\.npmrc.

**Solution**
Can you remove the need for the empty .npmrc file in the project directory? If it doesn't exist, it can then fallback to the user config as npm does with it's commands.

**Comment by yohanb** [comment]
hey @andrewfabrizi , thanks for the input.
That seems like a logical fix.  Will get to it.

**Comment by andrewfabrizi** [comment]
Thanks @yohanb!

**Comment by yohanb** [comment]
should be fixed!  Pull the latest version (1.0.6).
✌️

**Comment by andrewfabrizi** [comment]
It works! Thank you!

**Comment by yohanb** [comment]
my pleasure!
